/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_jni_Jni */

#ifndef _Included_demo_jni_Jni
#define _Included_demo_jni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_jni_Jni
 * Method:    heyMath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_jni_Jni_heyMath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
